# Generated by Django 3.2.13 on 2022-06-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('roles', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
