# Generated by Django 3.2.13 on 2022-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodityinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ordererid', models.CharField(max_length=100)),
                ('purchase_amount', models.FloatField(max_length=100)),
                ('purchase_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='price',
            field=models.FloatField(default=500),
        ),
    ]
