# Generated by Django 3.2.13 on 2022-06-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220613_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='price',
            new_name='money',
        ),
    ]
